### ISSUE TITLE
Request: Reporter Error Threshold

### ISSUE THREAD

**Issue by shellscape** [cedx/david.gulp#3]
I'd like to request that the plugin be configurable to throw an error if the number of out of date dependencies exceeds a set threshold.

Something like:

```
gulp.task('checkDependencies', function() {
  return gulp.src('package.json')
    .pipe(david({ threshold: 10 )); // throws error if more than 10 deps are out of date
});
```

**Comment by cedx** [comment]
Why not? It is very easy to implement.
Two solutions:
- be patient! I will code this when I have enought free time (in about 2 weeks).
- submit a pull request: every contribution is welcome.

**Comment by cedx** [comment]
I want to keep the package API as closest as the [David](https://github.com/alanshaw/david) one.
So I have updated the [sample `gulpfile.js`](https://github.com/cedx/david.gulp/blob/master/example/gulpfile.js) file to provide an implementation of this kind of feature.

**Comment by cedx** [comment]
Finally, I've implemented the requested feature as `errorDepCount` option, in version 0.3.3.
